// ─── Employee enums (matching DB ENUM columns exactly) ────────────────────────

import { ReactNode } from "react";

export type Genre = 'H' | 'F';

export type Department =
  | 'RH'   // Ressources Humaines
  | 'IT'   // Informatique
  | 'FIN'  // Finance
  | 'COM'  // Communication
  | 'DIR'  // Direction
  | 'OPS'  // Opérations
  | 'JUR'  // Juridique
  | 'MKT'; // Marketing

export type Poste =
  | 'AGT'  // Agent
  | 'CSL'  // Conseiller
  | 'AUD'  // Auditeur
  | 'INF'  // Informaticien
  | 'CMP'  // Comptable
  | 'JUR'  // Juriste
  | 'FOR'  // Formateur
  | 'CDP'; // Chef de Projet
export interface Employee {
  affectation: string;
  genre: string;
  id: string;
  matricule: string;
  firstName: string;
  lastName: string;
  cin: string;
  email: string;
  phone: string;
  department: string;
  poste: string;
  dateEmbauche: string;
  photoUrl?: string;
}

// ─── Formation enums (matching DB ENUM columns exactly) ───────────────────────

export type FormationCategory =
  | 'Technique'
  | 'Management'
  | 'Sécurité'
  | 'Soft Skills'
  | 'Réglementaire';

export type FormationStatus = 'Planifiée' | 'En cours' | 'Terminée' | 'Annulée';

export type ModeFormation = 'FIAI' | 'FD' | 'FIAE' | 'FIP' | 'FPP';

export type FactureStatus = 'Réglée' | 'Non réglée' | 'Annulée';

export type EtatDossier = 'Complet' | 'Ristournable';

// ─── Formation interface (mirrors `formations` table schema) ──────────────────

export interface Formation {
  numero_formation: string;    // PK — ex: "2026/001"
  theme: string;               // titre de la formation
  description: string;
  dateDebut: string;           // "YYYY-MM-DD"
  dateFin: string;             // "YYYY-MM-DD"
  category: FormationCategory;
  status: FormationStatus;
  lieu: string;
  formateur: string;
  maxParticipants: number;     // default: 20
  modeFormation: ModeFormation;
  montant: number;             // decimal(10,2)
  facture: FactureStatus;      // default: 'Réglée'
  etatDossier: EtatDossier;    // default: 'Complet'
  created_at?: string;         // auto-generated by DB
  participantIds: string[];    // ⚠️ Non présent en DB — à gérer via une table
                               //    de jointure (ex: formation_participants)
}

// ─── FormationRequest ─────────────────────────────────────────────────────────

export interface FormationRequest {
  justification: ReactNode;
  matricule: string;
  category: ReactNode;
  id: string;
  employeeId: string;
  title: string;
  description: string;
  status: 'En attente' | 'Approuvée' | 'Refusée';
  dateRequest: string;
}